### ISSUE TITLE
Numpy version mismatch in the first try

### ISSUE THREAD

**Issue by mahmoodn** [google/tf-quant-finance#49]
Hi
I have successfully installed tensorflow and tf-quant-finance from source, however, when I want to run an example, I get an error about version mismatch of numpy.

```
$ python3 American_Option_Black_Scholes.py
2021-04-02 08:52:17.384836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "American_Option_Black_Scholes.py", line 8, in <module>
    import tensorflow as tf
  File "/home/mnaderan/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mnaderan/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/home/mnaderan/.local/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 37, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "/home/mnaderan/.local/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 23, in <module>
    from tensorflow.python._pywrap_tf_session import *
ImportError: SystemError: <built-in method __contains__ of dict object at 0x7f4c43c1d600> returned a result with an error set
```

The versions are shown below

```
$ pip3 list | grep numpy
numpy                   1.19.5
$ pip3 list | grep tensor
tensorboard             2.4.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.6.0
tensorflow-estimator    2.4.0
tensorflow-probability  0.12.1
$ pip3 list | grep quant
tf-quant-finance        0.0.1.dev25
```
How can I fix that?

**Comment by cyrilchim** [comment]
Hi Mahmood,

Sorry for the late reply. Could you please clarify how and which example you run?

**Comment by mahmoodn** [comment]
It seems that there is an incompatibility between tensorflow and numpy 1.20 at the moment.
https://github.com/tensorflow/tensorflow/issues/48271

**Comment by cyrilchim** [comment]
Closing for now.
